language: ruby
rvm:
- 2.4.2
script:
 - bundle exec rubocop
notifications:
  irc:
    channels:
      - "irc.chew.pro#Chewbotcca"
    template:
      - "[\0003 2%{repository_name}] \0003 7%{author}\0003  \0003 3%{commit} \0003 (\0003 3%{branch}\0003 ) - \0002 %{commit_message}"
      - "Build #%{build_number}: %{message} in %{time_elapsed}. %{build_url}"
